### ISSUE TITLE
Error on database setup

### ISSUE THREAD

**Issue by DarkDeyus** [schemen/m2em#11]
I'm using Windows 10. During the database setup (m2em.py --create-db ) i receive an error:
AttributeError: 'SqliteDatabase' object has no attribute 'get_conn'

Whole traceback:
`Traceback (most recent call last):
  File "C:\Users\aaa\dev\m2em\m2em.py", line 400, in <module>
    me = M2em()
  File "C:\Users\aaa\dev\m2em\m2em.py", line 41, in __init__
    helper.createDB()
  File "C:\Users\aaa\dev\m2em\bin\Helper.py", line 29, in createDB
    create_tables()
  File "C:\Users\aaa\dev\m2em\bin\Models.py", line 52, in create_tables
    db.get_conn()
AttributeError: 'SqliteDatabase' object has no attribute 'get_conn'`

**Comment by DarkDeyus** [comment]
The reason of this problem is that the peewee changes in 3.0 are not backwards compatible.

https://github.com/coleifer/peewee/blob/master/docs/peewee/changes.rst

**Comment by schemen** [comment]
Heh, I'll have a look -  I need to clean up this project anyway!

Thanks for the notice

**Comment by schemen** [comment]
For now I have frozen the packages that work in the requirements.txt. I should've done that earlier anyway :)

I've also create a new issue for migrating to peewee 3.x #13
