### ISSUE TITLE
MangaFox changed website

### ISSUE THREAD

**Issue by schemen** [schemen/m2em#18]
Need to fix the parsers for that :)

* Verify Rssfeed working
* Verify parser working again

**Comment by schemen** [comment]
There is a kinda working version in the fix_mangafox branch, but it's definitely not ideal as it uses a headless browser. The new Mangafox uses a javascript based reader.

**Comment by eipind** [comment]
I think I've solved this problem, but I've only done it for the individual manga RSS feeds and I had to use selenium because of the way mangafox dynamically shows the manga pages. If there's a better way let me know, if not I'll create a PR soon

**Comment by schemen** [comment]
@eipind Thanks for your input! I have also worked with selenium in my potential fix: https://github.com/schemen/m2em/tree/fix_mangafox

We can compare code and see how to continue. I really don't like selenium as it slows down super and is hard to work with in a docker image (I still need to fix that somehow).

**Comment by eipind** [comment]
@schemen I must've half read your comment half asleep, sounds like I just repeated your work haha. No problem, I'll push onto a different branch. And I've been googling around and https://scrapy.org seems like a solution.

**Comment by schemen** [comment]
Mh I wanted to use scrapy for a while, I think I have a branch up where I experimented with it a bit. I didn't know scappy supports dynamic content though - I need to read through that a bit again.

**Comment by schemen** [comment]
One idea I had is to analyze the entire javascript requests and recreate those - that's significant effort and I don't know where and how to do that :D

**Comment by eipind** [comment]
Yeah, I think scrapy does and it looks like reproducing the Ajax queries actually seem possible https://www.codementor.io/codementorteam/how-to-scrape-an-ajax-website-using-python-qw8fuitvi. And to see the requests fanfox makes we can use the Chrome Dev tools

**Comment by schemen** [comment]
Discussion at #20

**Comment by schemen** [comment]
I noticed the mobile mangafox website doesn't use javascript. I'll have a look at that!

**Comment by schemen** [comment]
Never mind that, they seem to censor quite bit on their mobile app. 

@eipind I tried out splash and I have to say  I really like it. I rewrote some code and was able to get it quite performant. This of course requires to have splash running in the background as a "rendering-service" if you want to use Mangafox. This is generally really no problem in a docker deployment.

I will publish some changes once I got some more code and testing done.

**Comment by eipind** [comment]
Ahhh I was hoping for the mobile route to be an easy solution 😅. With
scrapy have you noticed a difference in speed? Plus it looks like I'm going
to have to read up a bit more on Docker

**Comment by schemen** [comment]
@eipind I am not using scrapy, I use the requests library (normal, not requests-html) to deliver a payload to splash and wait for the rendered response. I can process the data just as before :) I just outsourced the rendering :)

**Comment by schemen** [comment]
Meanwhile, the m2em code is barely increased while the ability to handle javascript heavy website is added.

**Comment by eipind** [comment]
Oh, I understand. A big improvement from using selenium for sure

**Comment by schemen** [comment]
@eipind have a look at the latest commit. 
It's nowhere near as fast as raw non-JS websites, but still fast enough to be bearable :) I experimented a bit with some timeouts, blocking certain requests, automatically display "adult" content with a cookie.

There is also a docker setup instructions in the readme now, let me know if they're unclear.

**Comment by eipind** [comment]
Cool, I'll give it a go and let you know how it goes

**Comment by schemen** [comment]
Change the compose file to use the fix_mangafox tag to get the testing image:

https://hub.docker.com/r/schemen/m2em/tags

**Comment by schemen** [comment]
This has been working good with Splash so I will close this issue for now :)
