### ISSUE TITLE
General setup issues 

### ISSUE THREAD

**Issue by colelisiongaming** [schemen/m2em#22]
Hello I was wondering if there was anyway I could get your contact info. I am interested in figuring this out then making a YouTube video so new users like me can set this up hope to hear back from you!

**Comment by colelisiongaming** [comment]
@Schemen

**Comment by schemen** [comment]
Hi!

I would love to discuss it here so everybody can see the improvements :) I am quite sure the instructions are far from perfect. I am glad for any help in that regard, so what exactly is unclear to you? Which parts could I extend or clarify? 

Note that this is a CLI tool, ideally run on server (On a normal pc it's also just fine)
