### ISSUE TITLE
Integrate Union Mangas

### ISSUE THREAD

**Issue by richmont** [schemen/m2em#9]
Or another service that offers mangas in portuguese, please

**Comment by schemen** [comment]
Hi! I can have a look at it, else you could also contribute =)

**Comment by schemen** [comment]
@richmito if you can find a service that offers RSS I could have a look at it

**Comment by richmont** [comment]
I'm searching, I will reply soon. Thanks for attention :)

**Comment by richmont** [comment]
https://readms.net/rss

Here

**Comment by richmont** [comment]
I not found the Union Mangas rss feed (I know it have feed because is the main source of pt-br mangas on Manga Rock app), but discovered the Central de Mangás rss feed:
http://cdmnet.com.br/rss

**Comment by schemen** [comment]
I'll have a look at this!

**Comment by schemen** [comment]
@richmont I have added the parses to the devel branch, sorry for the very long delay :D 

Can you test it out?
